//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportadorXlms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class importacao
    {
        public int id { get; set; }
        public int cliente_id { get; set; }
        public int origem_id { get; set; }
        public int destino_id { get; set; }
        public int aeronave_id { get; set; }
        public int filial_id { get; set; }
        public Nullable<int> schedule_mensal_detalhe_id { get; set; }
        public string usuario_id { get; set; }
        public Nullable<System.DateTime> data_conclusao { get; set; }
        public Nullable<System.DateTime> data_cancelamento { get; set; }
        public string voo { get; set; }
        public string prefixo { get; set; }
        public string observacao { get; set; }
        public string motivo_cancelamento { get; set; }
        public string tipo_ordem_servico { get; set; }
        public Nullable<bool> proximo_dia { get; set; }
    }
}
