SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ValidarRota]
AS
BEGIN
DECLARE @DATA AS DATETIME = CONVERT(datetimeoffset, CURRENT_TIMESTAMP) AT TIME ZONE 'Bahia Standard Time'

--INSERE NOTIFICACOES DE ATRASO NA ROTA 
INSERT INTO MOVIMENTONOTIFICACOES(COLABORADORFK,DATACADASTRO,ENVIACOLABORADOR,ENVIAEMPREGADOR,IDLIVRE,LIDO,MENSAGEM, PRECISARETORNO, TIPO, BAIXADO)
SELECT
	C.COLABORADORID,
	CONVERT(datetimeoffset, CURRENT_TIMESTAMP) AT TIME ZONE 'Bahia Standard Time',
	1,
	1,
	0,
	0,
    'Rota ' + CONVERT(VARCHAR, @DATA, 103) + ' está atrasado!',
	1,
	2,
	NULL
FROM
	COLABORADOR C
	INNER JOIN ROTA R ON R.COLABORADORFK = C.COLABORADORID
WHERE
	C.ATIVO = 1
	AND DATEADD(MINUTE, 1, @DATA) > R.DATAHORA AND @DATA <= R.DATAHORA
	AND R.CONCLUIDO = 0
END
GO
